#!/bin/bash -e
#
# Entry point for one-shot signer container.  This should just do its
# business and exit.
#

die()
{
    echo "$@" 1>&2
    exit 1
}


SIGN=/sign

# User account to match signing area's owner.  This account will do
# the signing.

SIGNER_USER=signer
SIGNER_GROUP=signer
SIGNER_AREA_UID=$(stat -c %u "${SIGN}")
SIGNER_AREA_GID=$(stat -c %g "${SIGN}")

if [ "${SIGNER_AREA_GID}" -ne 0 ]
then
    groupadd -g "${SIGNER_AREA_GID}" "${SIGNER_GROUP}"
fi
if [ "${SIGNER_AREA_UID}" -ne 0 ]
then
    SIGNER_HOME=$(mktemp -d)
    # This forces useradd to create and populate the directory
    rmdir "${SIGNER_HOME}"
    useradd -u "${SIGNER_AREA_UID}" -g "${SIGNER_GROUP}" -m "${SIGNER_USER}" -d "${SIGNER_HOME}"
else
    # We're already root.  Be root.
    SIGNER_USER=root
fi

# The && and || work around having -e set.
su - "${SIGNER_USER}" -c "/entry-user '${SIGN}'" \
    && STATUS=$? || STATUS=$?

# Save this for outside the container.
echo "${STATUS}" > "${SIGN}/.doss-status"
