#!/bin/bash -e
#
# Entry point for one-shot signer container.  This should just do its
# business and exit.
#

set -e


die()
{
    echo "$@" 1>&2
    exit 1
}


SIGN=/sign

# User account to match signing area's owner.  This account will do
# the signing.

SIGN_USER=signer
SIGN_GROUP=signer
SIGN_AREA_UID=$(stat -c %u "${SIGN}")
SIGN_AREA_GID=$(stat -c %g "${SIGN}")

if [ "${SIGN_AREA_GID}" -ne 0 ]
then
    groupadd -g "${SIGN_AREA_GID}" "${SIGN_GROUP}"
fi
if [ "${SIGN_AREA_UID}" -ne 0 ]
then
    useradd -u "${SIGN_AREA_UID}" -g "${SIGN_GROUP}" -m "${SIGN_USER}"
else
    # We're already root.  Be root.
    SIGN_USER=root
fi

# After this, the container will be destroyed.
exec su - "${SIGN_USER}" -c "/entry-user '${SIGN}'"
